
make_vgq_col_names_better_latl <- function(raw.df) {
  col_names <- names(raw.df)
  col_names <- case_when(
    col_names == "VG_Shooters_Freq_1" ~ "fps_past.year_hours",
    col_names == "VG_Shooters_Screen_1" ~ "fps_past.year_small.screen",
    col_names == "VG_Shooters_Screen_2" ~ "fps_past.year_touch.screen",
    col_names == "VG_Action_Freq_1" ~ "arpg_past.year_hours",
    col_names == "VG_Action_Screen_1" ~ "arpg_past.year_small.screen",
    col_names == "VG_Action_Screen_2" ~ "arpg_past.year_touch.screen",
    col_names == "VG_Sports_Freq_1" ~ "sports_past.year_hours",
    col_names == "VG_Sports_Screen_1" ~ "sports_past.year_small.screen",
    col_names == "VG_Sports_Screen_2" ~ "sports_past.year_touch.screen",
    col_names == "VG_RTStrat_Freq_1" ~ "rts_past.year_hours",
    col_names == "VG_RTStrat_Screen_1" ~ "rts_past.year_small.screen",
    col_names == "VG_RTStrat_Screen_2" ~ "rts_past.year_touch.screen",
    col_names == "VG_Fantasy_Freq_1" ~ "tbrpg_past.year_hours",
    col_names == "VG_Fantasy_Screen_1" ~ "tbrpg_past.year_small.screen",
    col_names == "VG_Fantasy_Screen_2" ~ "tbrpg_past.year_touch.screen",
    col_names == "VG_LifeSim_Freq_1" ~ "tbs_past.year_hours",
    col_names == "VG_LifeSim_Screen_1" ~ "tbs_past.year_small.screen",
    col_names == "VG_LifeSim_Screen_2" ~ "tbs_past.year_touch.screen",
    col_names == "VG_Music_Freq_1" ~ "music_past.year_hours",
    col_names == "VG_Music_Screen_1" ~ "music_past.year_small.screen",
    col_names == "VG_Music_Screen_2" ~ "music_past.year_touch.screen",
    col_names == "VG_Other_Freq_1" ~ "other_past.year_hours",
    col_names == "VG_Other_Screen_1" ~ "other_past.year_small.screen",
    col_names == "VG_Other_Screen_2" ~ "other_past.year_touch.screen",
    col_names == "VG_Shooters_Freq_P_1" ~ "fps_before.past.year_hours",
    col_names == "VG_Shooters_Screen_P_1" ~ "fps_before.past.year_small.screen",
    col_names == "VG_Shooters_Screen_P_2" ~ "fps_before.past.year_touch.screen",
    col_names == "VG_Action_Freq_P_1" ~ "arpg_before.past.year_hours",
    col_names == "VG_Action_Screen_P_1" ~ "arpg_before.past.year_small.screen",
    col_names == "VG_Action_Screen_P_2" ~ "arpg_before.past.year_touch.screen",
    col_names == "VG_Sports_Freq_P_1" ~ "sports_before.past.year_hours",
    col_names == "VG_Sports_Screen_P_1" ~ "sports_before.past.year_small.screen",
    col_names == "VG_Sports_Screen_P_2" ~ "sports_before.past.year_touch.screen",
    col_names == "VG_RTStrat_Freq_P_1" ~ "rts_before.past.year_hours",
    col_names == "VG_RTStrat_Screen_P_1" ~ "rts_before.past.year_small.screen",
    col_names == "VG_RTStrat_Screen_P_2" ~ "rts_before.past.year_touch.screen",
    col_names == "VG_Fantasy_Freq_P_1" ~ "tbrpg_before.past.year_hours",
    col_names == "VG_Fantasy_Screen_P_1" ~ "tbrpg_before.past.year_small.screen",
    col_names == "VG_Fantasy_Screen_P_2" ~ "tbrpg_before.past.year_touch.screen",
    col_names == "VG_LifeSim_Freq_P_1" ~ "tbs_before.past.year_hours",
    col_names == "VG_LifeSim_Screen_P_1" ~ "tbs_before.past.year_small.screen",
    col_names == "VG_LifeSim_Screen_P_2" ~ "tbs_before.past.year_touch.screen",
    col_names == "VG_Music_Freq_P_1" ~ "music_before.past.year_hours",
    col_names == "VG_Music_Screen_P_1" ~ "music_before.past.year_small.screen",
    col_names == "VG_Music_Screen_P_2" ~ "music_before.past.year_touch.screen",
    col_names == "VG_Other_Freq_P_1" ~ "other_before.past.year_hours",
    col_names == "VG_Other_Screen_P_1" ~ "other_before.past.year_small.screen",
    col_names == "VG_Other_Screen_P_2" ~ "other_before.past.year_touch.screen",
    .default = col_names
  )
  names(raw.df) <- col_names

  return(raw.df)
}
